# Logistic Regression

In [1]:
# LR ---> When we have target data as categorical

# LR ---> Backend activation function --> sigmoid -->
# probablity ---> (0-1)
# threshold_value = 0.5
# if value > 0.5:
# return 1
# else:
# return 0

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("C:\\Users\\Saurabh\\OneDrive\\Desktop\\Databases\\num-panda dataset\\COVID_toy.csv")

In [4]:
df.head(3)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.impute import SimpleImputer

In [7]:
si = SimpleImputer()

In [8]:
df['fever'] = si.fit_transform(df[['fever']])

In [9]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
lb = LabelEncoder()

In [12]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [13]:
df.head(3)

age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0

In [14]:
x = df.drop(columns = ['has_covid'])
y = df['has_covid']

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x,y,
                                                   test_size = 0.2,
                                                   random_state = 42)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
lr = LogisticRegression()

In [19]:
lr.fit(x_train, y_train)

LogisticRegression()

In [20]:
y_pred = lr.predict(x_test)

In [21]:
from sklearn.metrics import accuracy_score

In [22]:
accuracy_score(y_test, y_pred)

0.75

In [23]:
from sklearn.metrics import confusion_matrix

In [24]:
confusion_matrix(y_test, y_pred)

array([[9, 4],
       [1, 6]])

In [25]:
df = pd.read_csv("C:\\Users\\Saurabh\\OneDrive\\Desktop\\Databases\\num-panda dataset\\Social_Network_Ads.csv")

In [26]:
df.head(3)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
lb = LabelEncoder()

In [29]:
df['Gender'] = lb.fit_transform(df['Gender'])

In [30]:
df.head(3)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0

In [31]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [32]:
x = df.drop(columns = ['Purchased'])
y = df['Purchased']

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
x_train, x_test, y_train, y_test = train_test_split(x,y,
                                                   test_size = 0.2,
                                                   random_state = 42)

In [35]:
from sklearn.linear_model import LogisticRegression

In [36]:
lr = LogisticRegression()

In [37]:
lr.fit(x_train, y_train)

LogisticRegression()

In [38]:
y_pred = lr.predict(x_test)

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
accuracy_score(y_test, y_pred)

0.8875

In [41]:
from sklearn.metrics import confusion_matrix

In [42]:
confusion_matrix(y_test, y_pred)

array([[50,  2],
       [ 7, 21]])

In [43]:
df.shape

(400, 5)

In [44]:
df = pd.read_csv("C:\\Users\\Saurabh\\OneDrive\\Desktop\\Databases\\num-panda dataset\\PLACEMENT.csv")

In [45]:
df.head()

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [46]:
df.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [47]:
x = df.drop(columns = ['placed'])
y = df['placed']

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
x_train, x_test, y_train, y_test = train_test_split(x,y,
                                                   test_size = 0.2,
                                                   random_state = 42)

In [50]:
from sklearn.linear_model import LogisticRegression

In [51]:
lr = LogisticRegression()

In [52]:
lr.fit(x_train, y_train)

LogisticRegression()

In [53]:
y_pred = lr.predict(x_test)

In [54]:
from sklearn.metrics import accuracy_score

In [55]:
accuracy_score(y_test, y_pred)

1.0

In [56]:
from sklearn.metrics import confusion_matrix

In [57]:
confusion_matrix(y_test, y_pred)

array([[10,  0],
       [ 0, 10]])

In [58]:
param_grid = [
    {'penalty':['l1','l2','elasticnet','none'],
    'C' : np.logspace(-4,4,20),
    'solver': ['lbfgs','newton-cg','liblinear','sag','saga'],
    'max_iter'  : [100,1000,2500,5000]
}
]


In [59]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(lr,param_grid = param_grid, cv = 3, verbose=True,n_jobs=-1)
clf

GridSearchCV(cv=3, estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': array([1.00000000e-04, 2.63665090e-04, 6.95192796e-04, 1.83298071e-03,
       4.83293024e-03, 1.27427499e-02, 3.35981829e-02, 8.85866790e-02,
       2.33572147e-01, 6.15848211e-01, 1.62377674e+00, 4.28133240e+00,
       1.12883789e+01, 2.97635144e+01, 7.84759970e+01, 2.06913808e+02,
       5.45559478e+02, 1.43844989e+03, 3.79269019e+03, 1.00000000e+04]),
                          'max_iter': [100, 1000, 2500, 5000],
                          'penalty': ['l1', 'l2', 'elasticnet', 'none'],
                          'solver': ['lbfgs', 'newton-cg', 'liblinear', 'sag',
                                     'saga']}],
             verbose=True)

In [60]:
best_clf = clf.fit(x,y)
best_clf.best_estimator_

Fitting 3 folds for each of 1600 candidates, totalling 4800 fits


C:\Users\Saurabh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
3120 fits failed out of a total of 4800.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
240 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Saurabh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Saurabh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\S

LogisticRegression(C=np.float64(0.23357214690901212))

In [61]:
print(f'Accuracy - : {best_clf.score(x,y):.3f}')

Accuracy - : 0.980


In [62]:
df = pd.read_csv("C:\\Users\\Saurabh\\OneDrive\\Desktop\\Databases\\num-panda dataset\\insurance - insurance.csv")

In [63]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [64]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [65]:
x = df.drop(columns = ['charges'])
y = df['charges']

In [66]:
from sklearn.model_selection import train_test_split

In [68]:
label_encoder = LabelEncoder()
df['gender'] = label_encoder.fit_transform(df['gender'])

X = df[['gender', 'age']]
y = df['target']

KeyError: 'gender'

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,
                                                   test_size = 0.2,
                                                   random_state = 42)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression()

In [ ]:
lr.fit(x_train, y_train)